### ISSUE TITLE
Ambiguous call in nuget package 1.10.20.0

### ISSUE THREAD

**Issue by jphellemons** [DropNet/DropNet#143]
as in the samples from 
http://dkdevelopment.net/what-im-doing/dropnet/

var metaData = _client.GetMetaData("/Public");

will tell you that the call is ambiguous in nuget package 1.10.20.0

The call is ambiguous between the following methods or properties: 'DropNet.DropNetClient.GetMetaData(string, string, bool, bool)' and 'DropNet.DropNetClient.GetMetaData(string, bool, bool)'

var md = client.GetMetaData(null, path, false, false); // crashes
var md = client.GetMetaData(path, false, false); // seems to fill my path variable in the hash variable?

**Comment by sdbarron** [comment]
Workaround could be to put in the commas needed to make it specific:

    var metaData = client.GetMetaData("/Public", , False, False);

I'm not saying it's **good** but it should get you through!

**Comment by jphellemons** [comment]
Thank you for the workaround!
