### ISSUE TITLE
iWebProxy now required by constructor when not WindowsPhone

### ISSUE THREAD

**Issue by sdbarron** [DropNet/DropNet#144]
While I'm sure adding a proxy option is a great new feature, it would be nice if it were optional.

**Comment by sdbarron** [comment]
Workaround:  Pass in "Nothing"

**Comment by sdbarron** [comment]
I'm pretty sure this was fixed but the GitHub issue isn't closed.  Can/should I close it?

**Comment by dkarzon** [comment]
This should be fixed in the latest version from nuget as well.
