### ISSUE TITLE
Search function not generating request

### ISSUE THREAD

**Issue by tcuevas92** [DropNet/DropNet#146]
I'm using the client in sandbox mode and attempting to call the search function with a search string and path. After calling client.Search(searchText, path), my program hangs and no exceptions are thrown. I used fiddler to try to debug the issue and I don't see the search request ever being sent.

**Comment by dkarzon** [comment]
I think the problem here was an infinate loop within the search function. It was fixed with PR #145 

If possible you could try the package for v1.10.21 from the build https://ci.appveyor.com/project/dkarzon/dropnet/build/1.10.21/artifacts
If that works I'll publish it.

**Comment by tcuevas92** [comment]
Updating to the new version fixed my issue. Thanks for the quick response.

**Comment by dkarzon** [comment]
:+1: Just published the new version to Nuget.
