### ISSUE TITLE
Compiler Error CS0121

### ISSUE THREAD

**Issue by trienow** [DropNet/DropNet#147]
I am having problems with the compiler not being able to differentiate between two different methods with the same name.
The compiler says:

```
The call is ambiguous between the following methods or properties:
"DropNet.DropNetClient.GetMetaData(string, string, bool, bool)" and
"DropNet.DropNetClient.GetMetaData(string, bool, bool)"
```

**Comment by vyacheslav-lonschakov** [comment]
It's methods overload problem:

```
public MetaData GetMetaData(string hash = null, bool list = false, bool include_deleted = false)
public MetaData GetMetaData(string path, string hash = null, bool list = false, bool include_deleted = false)
```

If you're first argument is "path", write like this:
`var metaData = client.GetMetaData("/Public/DropboxManagement/Logs", null);`

**Comment by trienow** [comment]
Thanks for the reply, I'll keep it in mind!
The project, which used DropNet, has been abandoned, so unfortunately I can't 100% confirm your suggestion on my end.
