### ISSUE TITLE
AccessToken expiration

### ISSUE THREAD

**Issue by tomdeleu** [DropNet/DropNet#148]
I successfully created a sample application in which I can authenticate in Dropbox, save the access token, and upload a file... With the same access token I'm able to upload multiple files... All good.

However, after some time (didn't stopwatch it, but seems like 10-20 minutes) the token stops working. I don't get an exception. The file just isn't uploaded anymore and nothing happens.
(However, a search on the internet indicated the access token of dropbox never expires automatically)

Any ideas?

**Comment by dkarzon** [comment]
I have never seen that before. Can you upload the sample application you have with this issue?

Also is the API key you're using a dev only key or production? (shouldn't matter but worth testing)

**Comment by tomdeleu** [comment]
Solved it myself :) Should have set the "UseSandbox" flag to true.

Nonetheless, weird behaviour when it's not set correctly. But this solved my issue :)
