### ISSUE TITLE
Is it still working with the new dropbox update?

### ISSUE THREAD

**Issue by JerryT20** [DropNet/DropNet#160]
Is it still working with the new dropbox update?
Thanks

**Comment by RickySan65** [comment]
nope, not working..

**Comment by JanZeman** [comment]
Hello, please read the freshly added note: Development of DropNet has stopped!
DropNet is no longer under development and the current version of the library does not work with Dropbox API v2. I recommend moving to the official Dropbox .net SDK - https://github.com/dropbox/dropbox-sdk-dotnet

I myself was rather a user than the contributor of this nice library - only helped with few bug fixes. After Dropbox API v2 was announced I moved to that one (beginning of 2017) and it was a very easy move so I can only recommend...
